query Issue($login: String!, $last: Int!, $before: String) {
  user(login: $login) {
    issues(last: $last, before: $before) {
      pageInfo {
        startCursor
        endCursor
      }
      edges {
        node {
          title
          url
          repository {
            name
            owner {
              login
            }
          }
          updatedAt
          author {
            login
            url
          }
        }
      }
    }
  }
}
